
LIBTOIFS:CMD PROMPT('send library to IFS')

  PARM KWD(LIBRARY) TYPE(*CHAR) LEN(10) +
       PROMPT('LIBRARY TO SEND TO IFS')

  PARM KWD(TODIR) TYPE(*CHAR) LEN(200) DFT('/tmp') +
       PROMPT('DIRECTORY TO SAVE LIBRARY TO')